Page loads from a list of possibly test text
danielduffield/typing-test pull request #10
Opened 2017-06-10 06:48 UTC by danielduffield

Created an array with possible typing tests to be selected at random, refactored to make this possible, thereby making the code more flexible.

2017-06-10 06:50 UTC, danielduffield commented
![screen shot 2017-06-09 at 11 49 45 pm](https://user-images.githubusercontent.com/29046343/27000781-5ab5a4e2-4d6e-11e7-83f8-5464bcda78ad.png)

2017-06-10 22:04 UTC, thebearingedge requested changes

2017-06-10 22:04 UTC, thebearingedge commented on styles.css
> +  -webkit-animation: highlight-selected 1s infinite; /* Safari 4+ */
In general, you can omit CSS vendor prefixes unless you know for sure that you need to support finicky browsers.
https://caniuse.com/#search=animation
I recommend just sticking with `animation` here.

2017-06-10 22:04 UTC, thebearingedge commented on styles.css
> +  -webkit-animation: highlight-selected 1s infinite; /* Safari 4+ */
Also, nice touch.

2017-06-11 21:43 UTC, thebearingedge requested changes
Sweet! Your Pull Request/Issue title could be slightly better though, maybe something like "User can take different typing tests."

2017-06-12 16:22 UTC, merged